name: flutter_vision3d
description: Framework for 2D and 3D image processing. Integrate with OpenCV, OpenNI2, Realsense2 and TensorFlow Lite.
version: 1.0.3
homepage: https://github.com/HedgeHao/flutter_vision3d
repository: https://github.com/HedgeHao/flutter_vision3d

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      # android:
      #   package: tw.hedgehao.flutter_vision3d
      #   pluginClass: FlutterVision3dPlugin
      linux:
        pluginClass: FlutterVision3dPlugin
      windows:
        pluginClass: FlutterVision3dPlugin
