name: flutter_vision
description: Framework for 2D and 3D image processing. Integrate with OpenCV, OpenNI2, Realsense2 and TensorFlow Lite.
version: 0.7.0
homepage:

environment:
  sdk: ">=2.16.1 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    platforms:
      # android:
      #   package: tw.hedgehao.flutter_vision
      #   pluginClass: FlutterVisionPlugin
      linux:
        pluginClass: FlutterVisionPlugin
      windows:
        pluginClass: FlutterVisionPlugin
